services:
  nextjs:
    build: .
    container_name: nextjs
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME:-root}:${MONGO_INITDB_ROOT_PASSWORD:-password}@mongodb:27017/project
    restart: unless-stopped
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "28017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
volumes:
  mongodb_data:
networks:
  default:
    driver: bridge
